# Config file of ${project.name}.
# This file was originally created by version ${project.version}.

# The language file used by the plugin. This will generate a file
# with that name in this directory, which you can then customize
# to edit the messages of this plugin.
# These pre-made files are available in this plugin:
# - translations-en.yml
# - translations-es.yml (by TheCiROMG)
# - translations-fr.yml (by Kervinou)
# - translations-nl.yml
# - translations-zh.yml (by 2125368097)
# For other languages, you'll get the English translations as a
# starting point. It is highly appreciated if you submit your
# translations to the plugin author, so that others can use them
# too. Danke schön, gracias, dankon and спасибо!
languageFile: translations-en.yml

# The updater. Possible values:
# AUTO_INSTALL - check for updates, install new files when possible, otherwise
#                notify the server admins
# JUST_NOTIFY - check for updates, notify the server admins
# DISABLED - don't check for updates
#
# Before installing an update, the plugin checks that
# a) the new file is compatible with your Minecraft version
# b) the file is hosted at https://dl.dropboxusercontent.com/s/0v7euy3bp7jwcah
#    /blocklocker-VERSION.jar?dl=0 with VERSION the new version number, which
#    may only consist of digits and dots.
# c) it is safe to install this file automatically. When the file is flagged
#    as needing a manual installation by the plugin author, the file won't be
#    installed automatically
updater: DISABLED
# Some mod containers not has their own material name, they will store as
modContainers:
  - ic2_iridium_storage_box

# All types of containers that can be protected.
# All material names can be found here:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
protectableContainers:
- ANVIL
- BEACON
- BLACK_SHULKER_BOX
- BLUE_SHULKER_BOX
- BREWING_STAND
- BROWN_SHULKER_BOX
- BURNING_FURNACE
- CHEST
- CYAN_SHULKER_BOX
- DISPENSER
- DROPPER
- ENCHANTMENT_TABLE
- FURNACE
- GRAY_SHULKER_BOX
- GREEN_SHULKER_BOX
- HOPPER
- JUKEBOX
- LIGHT_BLUE_SHULKER_BOX
- LIME_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- ORANGE_SHULKER_BOX
- PINK_SHULKER_BOX
- PURPLE_SHULKER_BOX
- RED_SHULKER_BOX
- SILVER_SHULKER_BOX
- TRAPPED_CHEST
- WHITE_SHULKER_BOX
- WORKBENCH
- YELLOW_SHULKER_BOX

# When set to true, one sign protects all connected nearby blocks of the same
# type. When false, each container requires a separate sign.
# Please note that a double chest is one container, so one sign is enough to
# protect the whole chest, regardless of this setting.
connectContainers: false

# All types of doors that can be protected. These blocks must follow the data
# value format as described here:
# http://minecraft.gamepedia.com/Data_values#Door
protectableDoors:
- WOODEN_DOOR
- IRON_DOOR_BLOCK
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR

# All protections (except doors) that consist not only of the block listed here,
# but also of a supporting block. This is normally the block directly below.
# For example, for fence gates both the gate and the block below are protected,
# and signs can be attached to both.
# Note that for some blocks (like trapdoors, but also levers if you would add
# them here) the supporting block is not the block below, but the block it is
# attached on.
protectableAttachables:
- ACACIA_FENCE_GATE
- BIRCH_FENCE_GATE
- DARK_OAK_FENCE_GATE
- FENCE_GATE
- IRON_TRAPDOOR
- JUNGLE_FENCE_GATE
- SPRUCE_FENCE_GATE
- TRAP_DOOR



# The default amount of seconds a door stays open before closing automatically.
# Players can override this value by putting a [Timer:X] tag on the sign, where
# X is a number from 0 to 9.
# When using 0 or a negative value, the door will never close automatically.
# When the door was opened using redstone, the door will never close
# automatically too.
defaultDoorOpenSeconds: 0

# The amount of days the owner of a chest can be absent before the chest is
# unlocked. When zero or negative chests never expire.
#
# This setting will only work for online mode servers (or offline mode servers
# behind an online mode Bungee proxy). The reason is as follows. The last login time
# is stored in the player file. To access this player file, you nowadays need the UUID
# of the player. In offline mode, the UUID depends on the case-correct username. In
# other words: if a player (intentionally or not) puts the wrong cases on the sign
# (like notch instead of Notch), the chest protection would never expire. This behaviour is
# undesired, so chest expiration has been disabled altogether in offline mode.
autoExpireDays: 0

# Aside from players breaking protections, this plugin also prevents other things
# (creepers and TNT for example) from breaking protections. You can add things here
# if you want those things to destroy protections.
# For example,  allowDestroyBy: [CREEPER, TNT]  allows creepers and TNT to destroy
# protections.
#
# These are the values you can use, along with how they can destroy protections.
# CREEPER - creepers can destroy protections by exploding
# ENDERMAN - endermans can destroy protections by picking up blocks
# FIRE - fire can burn protections
# GHAST - ghasts can shoot exploding fireballs
# PISTON - pistons can remove the protection signs
# SAPLING - saplings can grow trees, destroying protection signs
# TNT - TNT can destroy protections by exploding
# ZOMBIE - zombies can destroy protected doors
# UNKNOWN - special value for all other unrecognized attacks
allowDestroyBy: []
